### ISSUE TITLE
Need contact infomation

### ISSUE THREAD

**Issue by musixhine** [UQ-UQx/optimus_ingestor#3]
Hi there,
I work for the LTS department @ Wellesley College in the U.S... My boss is currently asking me to install this project and somehow I have another project that relates to edX local installation.
I am still pretty new to this system. So I wish I can get some ideas and helps from you guys. 
I feel like to have your emails, so that I can ask you guys some stupid newbie questions~~~~ 
My email is pzhang2@wellesley.edu
Cheers!

--Gus 'AZ'

**Comment by uqxtechnical** [comment]
Hi there,

You can contact me (uqadekke@uq.edu.au<mailto:uqadekke@uq.edu.au>) to discuss the installation of the ingestor/dashboard.  With regards to edX, the system doesn’t integrate directly with edX, rather it uses the research package which edX.org<http://edX.org> provides to universities once a week (via AWS).  As for running them side by side, it should be okay, but there may be python package version incompatibilities.

Hope this helps,
cheers
Andrew

On 6 Feb 2015, at 12:14 am, Augustus P Zhang <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,
I work for the LTS department @ Wellesley College in the U.S... My boss is currently asking me to install this project and somehow I have another project that relates to edX local installation.
I am still pretty new to this system. So I wish I can get some ideas and helps from you guys.
I feel like to have your emails, so that I can ask you guys some stupid newbie questions~~~~
My email is pzhang2@wellesley.edu<mailto:pzhang2@wellesley.edu>
Cheers!

--Gus 'AZ'
